site_name: Asahi Linux 文書非公式日本語訳
site_url: https://asfdrwe.github.io/asahi-linux-translations/

repo_url: https://github.com/asfdrwe/asahi-linux-translations
repo_name: asfdrwe/asahi-linux-translations

nav:
  - ホーム: index.md
  - 機能対応:
    - 概要: platform/feature-support/overview.md
    - M1シリーズ機能対応: platform/feature-support/m1.md
    - M2シリーズ機能対応: platform/feature-support/m2.md
    - M3シリーズ機能対応: platform/feature-support/m3.md
    - M4シリーズ機能対応: platform/feature-support/m4.md
  - プロジェクト関連:
    - 用語集: project/glossary.md
    - FAQ: project/faq.md
    - Asahi-Linuxはいつ完成するの？: project/when-will-asahi-be-done.md
    - 参考資料: project/references.md
  - プラットフォーム文書:
    - Apple Silicon サブシステム: platform/subsystems.md
    - Appleプラットフォームセキュリティクラッシュコース: platform/security.md
    - 機器: hw/devices/device-list.md
    - コードネーム: hw/soc/soc-codenames.md
    - ディスプレイコントローラー: hw/soc/display-controllers.md
  - ユーザ向け:
    - Fedora Asahi Remix文書 <i class="fa-solid fa-arrow-up-right-from-square"></i>: https://docs.fedoraproject.org/en-US/fedora-asahi-remix/
    - 問題があるソフトウェア: sw/broken-software.md
    - 代替ディストリビューション: alt/alt-distros.md
  - 開発者向け:
    - 助っ人募集！: project/help-wanted.md
    - テザーブートセットアップ(開発者向け): sw/tethered-boot.md
    - m1n1:ユーザガイド ブートローダー: sw/m1n1-user-guide.md
    - Hypervisor: sw/m1n1-hypervisor.md
    - U-Boot: sw/u-boot.md
    - Devicetree bindings: sw/devicetree-bindings.md
    - Apple Silicon MacでのオープンOSエコシステム: platform/open-os-interop.md

theme:
  name: material
  language: ja
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: custom
      accent: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate

markdown_extensions:
  - toc:
      baselevel: 4
      permalink: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: ja
  - social:
      cards_layout_options:
        background_color: '#F4EAEA'
        color: '#2C2C2C'
